#:schema node_modules/wrangler/config-schema.json

name = "flower-helper-discord"
main = "./src/index.ts"
compatibility_date = "2024-09-26"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NODE_VERSION = "20.15"

[observability]
enabled = true

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
